import os
import click

def ensure_dir(path):
    if not os.path.exists(path):
        os.makedirs(path)

@click.group()
def cli():
    """TouchDesigner Framework CLI (tdfw)"""
    pass

@click.command()
@click.argument("app_name")
def start_app(app_name):
    """Scaffold a new TouchDesigner app"""
    base = os.path.abspath(app_name)
    ensure_dir(base)

    for folder in ["BAT", "DAT", "LOG"]:
        ensure_dir(os.path.join(base, folder))

    with open(os.path.join(base, "README.md"), "w") as f:
        f.write(f"# {app_name}\nGenerated by tdfw\n")

    with open(os.path.join(base, ".gitignore"), "w") as f:
        f.write("*.toe\n*.log\n")

    bat_path = os.path.join(base, "BAT", f"{os.path.basename(app_name)}.bat")

    with open(bat_path, "w") as f:
        f.write(f"""@echo off
set NODE=DEV
start "" "C:\\Program Files\\Derivative\\TouchDesigner\\bin\\TouchDesigner.exe" "{app_name}.toe"
""")

    for ext in ["StartupExt", "SettingsExt", "StateExt"]:
        ext_path = os.path.join(base, "DAT", f"{ext}.py")
        with open(ext_path, "w") as f:
            f.write(f"class {ext}:\n    def __init__(self, ownerComp):\n        self.ownerComp = ownerComp\n")

    click.echo(f"✅ Created TouchDesigner app scaffold at {base}")

@click.command()
@click.argument("ext_name")
def create_ext(ext_name):
    """Create a new extension stub"""
    path = os.path.join("DAT", f"{ext_name}.py")
    if not os.path.exists("DAT"):
        click.echo("❌ No DAT directory found. Run start-app first.")
        return

    with open(path, "w") as f:
        f.write(f"""class {ext_name}:
    \"\"\"{ext_name} description\"\"\"
    def __init__(self, ownerComp):
        self.ownerComp = ownerComp
""")
    click.echo(f"✅ Created extension stub: {path}")

cli.add_command(start_app)
cli.add_command(create_ext)
